apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  labels:
    app: payments-api
data:
  RabbitMq__Host: "rabbitmq"
  Payments__MaxApprovedAmount: "5000"
  ASPNETCORE_ENVIRONMENT: "Production"
